---
title: "Main title"
subtitle: "Sub title"
date: "`r format(Sys.Date(),  '%d %B %Y')`"
author:
  - name: Contact Name
    affiliation: Job title
    email: email@unhcr.org
output:
  unhcrdown::paged_simple:
paged-footnotes: true
links-to-footnotes: true
# uncomment this line to produce HTML and PDF in RStudio:
#knit: pagedown::chrome_print
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Normal

```{r, echo=FALSE, message=FALSE, warning=FALSE}
knitr::kable(head(iris, 8),
             format = "html",
             caption = "Population of concern to UNHCR for the last 5 years")
```

## Grey striped

```{r, echo=FALSE, message=FALSE, warning=FALSE}
knitr::kable(head(iris, 8),
             table.attr = "class=\'table-grey\'",
             format = "html",
             caption = "Population of concern to UNHCR")
```

\newpage

## Blue striped

```{r, echo=FALSE, message=FALSE, warning=FALSE}
knitr::kable(head(iris, 8),
             table.attr = "class=\'table-blue\'",
             format = "html",
             caption = "Population of concern to UNHCR")
```


## Narrow

```{r, echo=FALSE, message=FALSE, warning=FALSE}
knitr::kable(head(iris, 8),
             table.attr = "class=\'table-narrow\'",
             format = "html",
             caption = "Population of concern to UNHCR")
```

\newpage

## No border

```{r, echo=FALSE, message=FALSE, warning=FALSE}
knitr::kable(head(iris, 8),
             table.attr = "class=\'table-noborder\'",
             format = "html",
             caption = "Population of concern to UNHCR")
```
